name: KqueueCI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml-version:
          - 4.13.x
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
      - name: Install dependencies
        run: |
          opam pin add kqueue.dev -n .
          opam install -t . --deps-only
      - name: Build
        run: |
          opam exec -- dune build @install
